version: "2"

linters:
  enable:
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - ginkgolinter
    - gosec
    - reassign
    - staticcheck
    - unused
    - revive
    - nlreturn
    - lll
    - govet
    - gocritic
    - gocyclo
    - dupl
    - wrapcheck
    - prealloc
  disable:
    - tagalign
    - depguard
    - prealloc
    - wsl
  settings:
    lll:
      line-length: 150
    gocyclo:
      min-complexity: 25 # Adjust threshold as needed (e.g., 10, 15, 20)
    gocritic:
      disabled-checks:
        - exitAfterDefer
  exclusions:
    generated: strict
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      - path-except: _test\.go
        linters:
          - forbidigo

formatters:
  enable:
    - gofmt
    - goimports

# Options for analysis running.
run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 2
  tests: false
  go: '1.24'
  concurrency: 4