services:
  api-gateway:
    image: envoyproxy/envoy:v1.25.0
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - user-api

  user-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SRC_PATH: thouthtgears/shared-services
        SERVICE: user-api
    environment:
      K_SERVICE: user-api
      GOOGLE_PRROJECT: ${GCP_PROJECT_ID}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCP_REGION: ${GCP_REGION}
      PORT: 8081
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    depends_on:
      - otel-collector

  otel-collector:
    build:
      context: .
      dockerfile: metrics.dockerfile
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      K_SERVICE: user-api
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    ports:
      - "13133:13133"
