services:
  api-gateway:
    image: envoyproxy/envoy:v1.25.0
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - user-api
      - document-api

  user-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SRC_PATH: thoughtgears/shared-services
        SERVICE: user-api
    environment:
      K_SERVICE: user-api
      GOOGLE_PROJECT: ${GCP_PROJECT_ID}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCP_REGION: ${GCP_REGION}
      PORT: 8081
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: otel-collector:4317
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: otel-collector:4317
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_INSECURE: "true"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    depends_on:
      - otel-collector
    links:
      - otel-collector

  document-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SRC_PATH: thoughtgears/shared-services
        SERVICE: document-api
    environment:
      K_SERVICE: document-api
      GOOGLE_PROJECT: ${GCP_PROJECT_ID}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCP_REGION: ${GCP_REGION}
      GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
      PORT: 8081
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: otel-collector:4317
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: otel-collector:4317
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_INSECURE: "true"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    depends_on:
      - otel-collector
    links:
      - otel-collector

  otel-collector:
    build:
      context: .
      dockerfile: metrics.dockerfile
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/service-account.json
      K_SERVICE: user-api
    volumes:
      - ./data:/root/.config/gcloud
    ports:
      - "13133:13133"
      - "4317:4317" # GRPC endpoint
      - "4318:4318" # HTTP endpoint
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:13133" ]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  default:
    name: shared-services-network
    driver: bridge
