services:
#  api-gateway:
#    image: envoyproxy/envoy:v1.25.0
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./envoy.yaml:/etc/envoy/envoy.yaml
#    depends_on:
#      - portal-api
#    links:
#      - portal-api

  portal-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SRC_PATH: thoughtgears/shared-services
    environment:
      K_SERVICE: portal-api
      GOOGLE_PROJECT: ${GCP_PROJECT_ID}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCP_REGION: ${GCP_REGION}
      GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
      PORT: 8081
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
    ports:
      - "8080:8081"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud

